language: cpp

install:
  - sudo pip install cpplint
  - sudo apt-get install libboost-all-dev

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake -DTESTS=ON ..

script: make && make test
