language: cpp

install:
  - sudo pip install cpplint
  - sudo apt-get install libboost-all-dev

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake -DCPPRESTCONFIG_TESTS=ON -DCPPRESTCONFIG_SAMPLES=ON -DCMAKE_BUILD_TYPE=ReleaseWithDebInfo ..

script: make && make test
