language: cpp

install:
  - sudo pip install cpplint
  - sudo apt-get install libboost-all-dev

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
